#!/usr/bin/env bash

REP_DIR=/autograder/autograder-source
cd $REP_DIR
git pull >> gitlog.txt

COMMON_DIR=${REP_DIR}/common
cd ${COMMON_DIR}
# Get project name from submission_metadata.json
if ! python3 ProjectSelector.py ; then
    echo "{ \"score\":0, \"output\": \"Could not determine the project submission.  Redo submissions should be submitted with a changes.txt file.\", \"visibility\": \"visible\" }" >> /autograder/results/results.json
    exit 1
fi
source "/autograder/files.cfg"

PROJ_DIR=${REP_DIR}/${PROJ_NUM}
DEST_DIR=/autograder/playground/
mkdir ${DEST_DIR}

#cp -ar ${PROJ_DIR} ${DEST_DIR}
STUDENT_DIR=/autograder/submission/.



# Set up autograder files

if [ -d "${STUDENT_DIR}" ]; then

    # Copy starter code
    STARTER_DIR=${REP_DIR}/${PROJ_NAME}/solutions/starter/.
    if [ -d "${STARTER_DIR}" ]; then
        cp -ar ${STARTER_DIR} ${DEST_DIR}
    fi
    # Copy common tests
    cp -ar ${COMMON_DIR}/* ${DEST_DIR}
    # Copy student submission
    cp -ar ${STUDENT_DIR} ${DEST_DIR}
    # Copy specific tests
    TEST_DIR=${REP_DIR}/${PROJ_NAME}/tests/.
    cp -ar ${TEST_DIR} ${DEST_DIR}

    # TODO : Lock students


    # run tests
    cd ${DEST_DIR}


    make all 2>&1 | tee makeout.txt
    python3 run_tests.py
    python3 cpprunner.py

    # compile results
    python3 xmlparse.py
        
else
    echo "{ \"score\":0, \"output\": \"Directory not found: ${PROJ_NUM}\", \"visibility\": \"visible\" }" >> /autograder/results/results.json
fi
