#!/usr/bin/env bash

PROJECT=bracket

# # Configure settings for running SFML Headless
# export DISPLAY=:1
# Xvfb :1 -screen 0 1024x768x16 &

# Set up autograder files

#cp -a /autograder/submission/. /autograder/source/
#tar -xzf /autograder/submission/*.tar.gz -C /autograder/source/
cp -ar /autograder/source/solutions/starter/. /autograder/source/${PROJECT}/
cp -ar /autograder/submission/. /autograder/source/${PROJECT}/
cp -ar /autograder/source/tests/. /autograder/source/${PROJECT}/

cd /autograder/source/${PROJECT}

make all 2>&1 | tee /autograder/source/${PROJECT}/makeout.txt
python3 run_tests.py

cd cpptests
python3 cpprunner.py
cd /autograder/source/${PROJECT}

python3 xmlparse.py

